master_class:
  outputs:
    dev:
      catalog: dbt_tutorial_dev
      host: dbc-cf4b971a-ca25.cloud.databricks.com
      http_path: /sql/1.0/warehouses/ab280e04e9186d87
      schema: default
      threads: 1
      token:
      type: databricks
    prod:
      catalog: dbt_tutorial_prod
      host: dbc-cf4b971a-ca25.cloud.databricks.com
      http_path: /sql/1.0/warehouses/ab280e04e9186d87
      schema: default
      threads: 1
      token:
      type: databricks
  target: dev